### PR TITLE
Carbon Addons

### PR DESCRIPTION
**Pull request by loganmccaul**
This is a RFC proposing a new set of tooling and conventions for Carbon Addons.

This work stems from the Addon repository we have been building on IBM Cloud and is based on research that was conducted with various development teams working on the IBM Cloud platform and services that run on that platform.

This is definitely an extremely long RFC, there's a lot of partially completed thoughts in it. If you would like more details on anything let me know. Many of concepts have already been developed within our business unit.

# [VIEW RFC HERE](https://github.com/loganmccaul/rfcs/blob/master/text/0000-carbon-addons.md) <----------------

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thank you for gathering the thoughts on this! Defining the standards will be a great idea, the only concern I have is possible lost of freedom as you brought up. To alleviate this concern, I suggest the following:

1. Focus on tooling and templates, given using tool or not is up to add-on author
2. Define requirements in high-level, rather than details
3. Differentiate stronger requirement, mid-level requirement weaker requirement, rather than request to conform everything or nothing

**Comment by loganmccaul** [comment]
Thanks for the feedback @asudoh! I definitely agree that the focus should be on tooling and I think there is a lot of opportunity to make sure the tools also work as standalone packages to allow for Addon teams to choose what they need. 

I also love the idea of establishing a bit of a hierarchy around what's required and what's not. Maybe there's an opportunity to gather various stakeholders across different business units have a quick session to work out what we think we should be strict on what are more of guidelines.

**Comment by scottnath** [comment]
@loganmccaul @asudoh great stuff! Couple RFC-wide comments. Primary point being separating framework-specific items from framework-agnostic items.

## tooling requirements vs specific tooling choices

Focussing on specific tooling might make it difficult for non-React implementations. When determining add-on library structure, it would help to document expected  _functionality_ rather than specific tools to accomplish that functionality.

For instance, `Dev Server (Tooling)` - using `Parcel` to create a server might not be the best choice for the `carbon-vue` or `carbon-angular` and wouldn't work when creating Vanilla components. And on our team we've run into some issues with Parcel (such as bugs when creating `maps`). So for planning purposes, would it be possible to just focus on what an add-on library should be able to do, and then tooling could be determined from the functionality requirements? So, instead of

```
The Development server is a basic Parcel server that is used to develop the 
Carbon Addon components. This can be customized to use a custom server 
through the CLI so you can properly make API calls without CORs issues.
```

it could be:
```
The Development server is used to develop the Carbon Addon components. 
This server should be customizable to use a custom server through the CLI 
so you can properly make API calls without CORs issues.
```

The requirements could be a living document, getting updated as new needs arise. Once you have requirements, there would be subsequent `RFC`s to determine tooling that would be best suited to accomplish the functionality according to the technological ability of each framework. 

The second benefit of requirements vs specific-tooling-choices is around future-proofing the system. If there are functionality requirements in place, the tooling could be revisited in the future as technology matures (or is abandoned), making new choices according to the requirements instead of the old tool's functionality. 

This would also allow a new framework (*cough* web components *cough*) to determine tools from required functionality, rather than trying to use an existing tool which may not be the best choice for the new framework.

## framework agnostic vs framework specific

Another item is around folder structures, specific files and file-types and what would live in an add-on vs what's in the canonical.

For instance, the `File Structure` section - there are some files which would be framework-agnostic, like any of the .mdx files, but then that structure includes React-specific files like `(NAME).js`, which is not something that would exist in a [carbon-angular component](https://github.com/IBM/carbon-components-angular/tree/master/src/button) (which uses .ts files), a [carbon-vue component](https://github.com/carbon-design-system/carbon-components-vue/tree/master/packages/core/src/components/cv-button) (.vue files), or a [vanilla component](https://github.com/carbon-design-system/carbon/tree/master/packages/components/src/components/button) (.hbs files). 

So instead, it could be documented like so:


## Agnostic file structure

| File | Description | Prefilled Code (%) | Required |
|:------------- |:------------------------------|-----:| -----:|
| _styles.scss | Styles for this View component. Prefixed with a chosen prefix for this Addon. Styles are in scss to match how Carbon handles styling. | 01 | Yes|
|code.mdx| The documentation mark down file for this component. | 20 | Yes|
|usage.mdx| The design documentation for how this component should be used.| 00| Yes|
|style.mdx| Design documentation on the style of this component.| 00 |Yes|

## Storybook file structure

| File | Description | Prefilled Code (%) | Required |
|:------------- |:------------------------------|-----:| -----:|
| skeleton.js| The loading skeleton for this component. | 20|Yes|

## React add-on file structure

agnostic and storybook files plus:

| File | Description | Prefilled Code (%) | Required |
|:------------- |:------------------------------|-----:| -----:|
| index.js | Exports the View Component. | 100 | Yes|
| (NAME).js | The primary React component. | 20| Yes|
| (NAME)-test.js | The tests for the primary React component. |20| Yes|

## Vanilla add-on file structure

(if vanilla didn't use storybook, it would just inherit the agnostic files)
agnostic files plus:

| File | Description | Prefilled Code (%) | Required |
|:------------- |:------------------------------|-----:| -----:|
| (NAME).config.js | Exports the component configuration. | 100 | Yes|
| (NAME).hbs | The primary Vanilla template. | 20| Yes|
| tests/(NAME).spec.js | The tests for the primary Vanilla template. |20| Yes|


A change like this would work for any content, not just files. The main question being: "Is this a React-specific item, or would this item work with _all_ the frameworks".

This would also give us something to _test_. For all add-ons, Carbon would test for the existence of the `.scss` file and the three `.mdx` files, but then there would be react-add-on-library-specific tests for `(NAME).js`'s existence. These automated tests could ensure no add-on gets merged without the minimum-required files.

**Comment by loganmccaul** [comment]
@scottnath Thanks for bringing this up! I've been struggling on how to communicate this idea outside of the React world and the work we've already done within IBM Cloud. I definitely don't want Carbon Addons to be specific to one language, and the concepts themselves should be agnostic.

One idea I've been thinking of is breaking down templates by language. So instead of using a View template I would specifically use a React:View template. Those files can be made up of the language agnostic structure and the language specific files.

I'll spend some time tonight updating the RFC to remove the specific development solutions as well as the generalizing the work to be more broad than just React.

**Comment by loganmccaul** [comment]
@scottnath I've updated the RFC with more agnostic language. The primary changes are

- When initializing a Carbon Addons library a language needs to be selected.
- Templates are specific to a language and the required files and implementation details can differ per language. However, the general concept of a template can probably be shared across languages.
- Added possible file types for each template and removed any specific reference of React to reflect above.

Let me know if that helps, or if you feel that the RFC is still too specific about implementation details.

**Comment by joshblack** [comment]
Just to narrow in on things, could you expand on the goals section, namely:

> To decrease front end development time.

What specifically are we addressing and how do they contribute to decreasing development time?

> - To encourage consistency across a single business unit.
> - To create a centralized place for reusable front end development patterns within a business unit.

Is the second goal a way to achieve the first goal in this list? Or is it truly a goal in and of itself? If it's a standalone goal, what's the value of a centralized place for reusable FED patterns?

> To allow for more reusability across IBM and across business units.

How would this goal relate to the goal of creating consistency across a single business unit? Often times, they can feel like they contradict each other so was curious how you are thinking this could play out.

---

With respect to discrete aspects of this proposal, I think tooling could easily fall under the new [`@carbon/cli` package](https://github.com/carbon-design-system/carbon/tree/master/packages/cli).

I think our goal is to try and do both single-purpose CLI tooling, for example `@carbon/contribute` for contributing and `@carbon/upgrade` for upgrading, alongside a consolidated tool `@carbon/cli`. Under the hood, what this means is that single-purpose CLI tools will export their commands such that `@carbon/cli` can also register them.

I strongly agree with the fundamental project structure, namely how we build out components and docs for these components, and I feel like this can take on a shape that mirrors Carbon's structure. This would mean that any tooling we build into `@carbon/cli` (for example the sync command) could also be helpful in these projects, alongside any kind of scaffolding or running that we may bring into that package.

---

Ultimately, what I think we'll see happening is the formation of "design sub-systems". These inherit what they want from the broader "design system", but ultimately control how their brand delivers the design system in product.

On the design system side, this means that we open up our system into several categories:

- Elements: design elements from the design language represented in code
- Core components: components built and maintained by the core team
- Community components: components built and maintained by community contributors, these components have broad use but may have broad scope or require domain expertise that the core team lacks

Within each of these categories, we offer a combination of distinct, single-use packages alongside preconfigured bundles of functionality. For example, with elements we offer standalone packages for colors or type but ultimately bundle them together in a single package, `@carbon/elements`.

The job of the sub-system team is to then grab either preconfigured bundles, or craft their own bundles for how they want to deliver components in code for their particular brand. Hierarchy-wise, this may look like:

```
- design system
  - accordion
  - accordion-react
  - button
  - button-react
  - vanilla
    - accordion
    - button
  - react
    - accordion-react
    - button-react
```

The sub-system then has a couple of options:

```
# Use design-system/react directly
- sub-system
  - react
    - design-system/react
```

```
# Use components as-needed
- sub-system
  - react
    - design-system/button
```

The sub-system also is a place to start adding in layers brought up in this RFC, namely data/domain requirements for components. It also is the location to consolidate front-end code, namely around things like configuration for tooling, styles, and components themselves.

It also includes the documentation site reference in this RFC, and can pull in content from the upstream system (like component examples, guidance, etc.) so that referencing something in the sub-system is a one-stop shop, and will let us nest sub-systems as needed (a common problem now with add-ons is their hierarchy).

Obviously a lot of this stuff isn't worked out yet, but it does feel like we're starting to scratch at a similar itch when it comes to figuring out how to address the current add-on situation. Just wanted to leave some thoughts on this RFC for context, and to think about how we can further align things 😄

**Comment by loganmccaul** [comment]
Hey @joshblack! Thanks for the feedback, it's great to hear what the core Carbon team is thinking about!

I'd love to expand on the goals. 

### To decrease front end development time.
This is the time it takes to develop the product, not the component library. For components, the development time saved comes from reusing styles, actions, and patterns. Same as the value Carbon provides today.

Data Hooks and Connected components come from research within the Cloud business unit. We found that developers spent a significant amount of time learning and setting up APIs.  Data Hooks and Connected components exist to decrease the time it takes for a developer to use an API.

### To encourage consistency across a single business unit.
This goal does not directly impact development time. Instead, this goal derives from Cloud design's research. The research uncovered tons of different implementation patterns. This can lead to a whole multitude of UX issues. 

### To create a centralized place for reusable front end development patterns within a business unit.
A centralized place also allows for communication and awareness of patterns already created. Within Cloud, teams have created their own component libraries to share between microservices. Other teams can't discover and use the existing components because these are team specific .

You are right. This one is more of a solution to the above goal. I'll play around with the wording and update the RFC.

I'd love for you to expand a bit more on why a centralized location can lead to inconsistency across a single business unit. From our perspective we have a few different component libraries that could be considered addons. Each is maintained, built, and communicated differently across IBM Cloud. To us, a centralized location would allow for more collaboration between the team's developing on IBM Cloud. We might be going down the wrong path though.

I'll update the RFC with the above explanations.

<hr />

I love this! The more we could combine the Carbon Addons concepts and the Carbon tooling the more scalable each can be. I agree that the structure of an Addon and the structure of Core Carbon should align. Carbon can become more of a foundation and ecosystem for design systems than a single design system itself.

<hr />

These plans for a design sub system are great! It allows each business unit to control components and how they get used. Additionally, I love the plans you all have so far.

There is room to expand on both concepts. The data and domain specific stuff can all share a common tool set with the rest of Carbon's CLI. I can see a future where patterns such as "Login with IBMid" or other general IBM actions live within a core design system. Regardless, having one CLI would make it easier for business units to know what's available. It also allows for everything with the Carbon name to be built and developed the same way.

Maybe this RFC should take in the concepts you brought up above and be renamed `Carbon Ecosystem` 😄

**Comment by loganmccaul** [comment]
I reference ongoing work within the Cloud business unit as well as internal developer research in the RFC and my responses. If anyone is interested in learning more about those feel free to DM me and I'd be happy to share resources.

**Comment by vpicone** [comment]
@loganmccaul I've been thinking about this problem a lot. Essentially, applying Gatsby's theming model to design systems. I think by providing an infrastructure to develop, document and deploy bespoke components with Carbon at the engine, we could develop a really powerful design system architecture.

We’ve seen a similar problem play out in the IBM websites attempting to use the Carbon website as a model. Teams that originally cloned the repo, or devised their own solutions are coming back to use the Gatsby theme because the infrastructure makes it a happy path to best-practices and shared contribution. 

I wanted to stress the biggest advantages, in my opinion, from Carbon owning and supporting the tooling around addon development
- Owning the tooling and distribution pipeline means we gain insights into how teams are using Carbon and what they're making with carbon components
- We can make guarantees about the components, their dependencies, and the carbon version that would be much more difficult if we didn’t own the tooling
- We can use this use this information to make informed decisions about future core components
- Free, supported infrastructure means increased Carbon adoption, and easier migration to major versions

---

#### My **biggest concern** with the RFC as-is pertains to the Connected/Hosted components and Data Helpers.

This tooling seems out of context and prescriptive for a design system/front-end development kit to take an stance on. Teams might have their own opinions on things as simple as even using presentational/container-components. For example, Dan Abramov recently [walked back his opinion](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) on this pattern. The RFC pushes even further past that point of possible contention and gets into Hosted vs. Connected components? This sort of stance on data fetching at the business-unit level is untenable in my opinion.

In addition, by including things like data-fetching helpers we're pushing the scope of what logic gets put into an addon component while also restricting the teams that could take advantage of shared components. This makes it harder for us to support the addon infrastructure tooling and decreases the likelihood that a component could bubble up to core.

---
### Addon composability

I also wanted to share a couple ideas here that could be fundamental to flexible addon architecture and greatly increase their utility in a way I'm not sure exists for other component libraries yet. 

As is, addons would have a flat model whereby any team or individual could create an addon and it would be in a pool of peers. This could result in perhaps importing from several addons in addition to Carbon Core.

[Design System Tiers - EightShapes - Medium](https://medium.com/eightshapes-llc/design-system-tiers-2c827b67eae1)
core-9e66635a-a158-433d-9ea7-c1521a675186

An interesting model might be making these systems _composable_ (similar to Gatsby themes). In the end, addons and their documentation could all compose with each other as well as Carbon Core before shipping as a bespoke bundle or theme. I think this would result in the ideal dependency experience for developers importing and using an addon.

This would also allow us to develop tiers of addons with progressively stringent requirements (enabled per-addon through configuration). This pattern would both empower experimentation and flexibility **without risking the integrity of higher-quality, upper-tier addons** potentially shared between business units. We could have increasing requirements from code formatting to themability.

quality-criteria-c6445869-07c5-4f1b-9fa2-976770a5b664

Finally, I think a truly composable addon architecture could expand beyond the current component/react focused solution to include things like [themes](https://github.com/system-ui/theme-specification) as well as pure documentation via guidelines.

**Comment by loganmccaul** [comment]
Hey @vpicone! Sorry for the late response, I must've missed your comment. Thanks for taking the time to read and provide feedback!

I  agree about the Gatsby model. I actually haven't thought about this from the concept of Gatsby Themes. There is definitely a lot we can learn and understand from the way they've set things up.

I also completely agree with your assessment of advantages with one exception. Ownership and development of these tools needs to be shared across business units as well as Carbon. Carbon is definitely in the unique position to be at the center of the solution, but with the numerous different business units in IBM it may be an impossible task for one team to maintain a system and meet each org's needs.

<hr />

You bring up an excellent point about being too prescriptive with anything that is data connected. With templates I hope we're not enforcing any practices.  I can help share some of the background and template concepts that might be missing from the RFC.

First, when we began this work within IBM Cloud we started by interviewing different front end developers in our business unit. The number one pain point we found was around working with APIs. For the most part developers had every component they needed from Carbon, but they didn't have a way to understand or use the APIs that make up IBM Cloud. Without a place to share or reuse API calls, each team was spending a large amount of time reinventing the wheel. For us, one of our goals was to minimize reinvention. I don't want to go into too much detail on the research here, but if you're interested I'd be happy to share a lot of our research findings internally.

Second, we should never enforce specific development patterns. That's one of the reasons why templates need to be extensible. The Data Hooks and Connected components in the RFC are examples of components that work well for IBM Cloud. There's no reason a template can't exist for other data driven aspects. Apollo queries or basic fetch requests could be templates for example. Hopefully, if an existing template doesn't meet a developers need then they will create a new one. It's one of the reasons that a Connected component is made up of Data Hooks and Views. It allows the developer to decide which component they want to use. Connected gives them the full picture, Data Hook gives them the data, and View gives them the look and feel with each functioning on it's own. (Except Connected I guess :smile: )

I do agree that data fetching, smart components, or anything specific to an API doesn't make sense in core Carbon, but they can provide significant value for product developers. This is one of the reasons that I'm hoping the creation of these tools becomes shared across business units. Each business unit has their own needs. If we share the solutions to those needs we may find a lot of opportunity to reuse code across IBM.

<hr />

This is really cool! I'm unfortunately not too familiar with how Gatsby theme's work under the hood, but if we we're able to streamline and share work through composing existing patterns we can truly create an extensive system.

I also really like the idea of this being more than a component library and instead a pattern of best practices, tools, and assets that allow each group down to the individual development team to share and form their own environments.

I'd love to learn more about how this could work from a technical perspective if you have time. There's also an opportunity for a bit of a workshop here to share and combine the different concepts that are being discussed.

**Comment by vpicone** [comment]
@loganmccaul, I didn't realize quite how far you guys were along in the path towards making this a reality for your team. This this next coming milestone I think we plan on dedicating the time and resources to get this right across business units.

In regards to tool ownership, I definitely don't mean owning the individual addons or even necessarily the space where addons live, I mean the tools and infrastructure for building addons with carbon that have portability between business units as a primary directive. The first image my comment is what we _don't_ want, the tooling I'm talking about owning is much closer to the arrows and foundations of the addons than the addons themselves. That tooling, I think, could be sufficiently abstracted across teams and business units and provided open source via Carbon.

### Re: data stuff
I think one thing we might differ on is the end goal of addons.
1. Empower BU and teams to distribute and reuse accessible components built with Carbon
2. Allow for the distribution of those same components across business units at IBM, fostering an ecosystem of shared interest

The ultimate challenge here is going to be crushing `1.` while at the same time not sacrificing the ability of us and future developers to crush `2.`

By including hooks, caching, and opinionated data logic in a third party component library, we stand the risk of exposing/depending on business logic that makes these addons not only closed source, but also prevents us from accomplishing `2.`

As someone who came from writing product code to the framework side, I can definitely empathize with the front-end developers API plight. While I think cloud should certainly be empowered to write and share their own data driven components, I have a really uneasy feeling of incorporating data fetching architecture into components meant as an addon to a third party component library.

Could you imagine if libraries like material-ui, semantic-ui, or polaris had opinionated data fetching elements to their component libraries? Although you're separating concerns between view and data components, intermingling those concerns in the library as a whole will invariably grow to serve the business units needs and make those components less and less portable across BU lines.

I'd _implore_ you to reconsider including the data hooks in this RFC and distributing them separately for both the increased portability of the addon components and the flexibility in maintaining your data fetching hooks.

**An example:** what if you had to make a breaking change to one of your data fetching hooks do to an API change? Now you have to make a breaking change to the component library as well and version appropriately. To me it just doesn't make sense having these things in the same package just for the convenience of a single import. There's also nothing stopping you from packaging `carbon-addons-cloud` and `react-hooks-cloud` into a single `cloud-ui` package. I think we really, really just don't want them to intermingle, it drastically over complicates the scope of addons and the tooling around it.

I hope that wasn't too dramatic haha, really looking forward to figuring this out together.

**Pull request closed without merging**
